## TEST LOCALLY

### upload a doc
POST http://localhost:7071/api/IngestData HTTP/1.1
content-type: application/json

{
    "FilePath": "input.txt"
}

### ask a question to your email
POST http://localhost:7071/api/PromptData
Content-Type: application/json

{"Prompt":"What can i do for giving campaign"}

## TEST IN AZURE (do `azd provision` first)

### set URL and x-functions-key to correct values for your Azure FunctionApp

### upload an email
POST https://func-api-***.azurewebsites.net HTTP/1.1
content-type: application/json
x-functions-key: ***

{
    "FilePath": "input.txt"
}

### ask a question to your email
POST https://func-api-***.azurewebsites.net/api/PromptEmail
Content-Type: application/json
x-functions-key: ***

{"Prompt":"what time to I need to be at the venue? "}
